## 作业准备

作业说明: [slide](https://docs.google.com/presentation/d/18MG1wSTTx8AentGnMfIRUp8ipo8bLpgAj16bJoqW-b0/edit#slide=id.g4cd6560e29_0_10) [video](https://youtu.be/QfU-qXINCvs)

数据下载: [data](https://www.kaggle.com/c/ml2020spring-hw1/data)

In [1]:
import pandas as pd

In [2]:
import numpy as np

In [3]:
train_data = pd.read_csv('train.csv', encoding='big5')

In [4]:
train_data.head(20)

,日期,測站,測項,0,1,2,3,4,5,6,...,14,15,16,17,18,19,20,21,22,23
0,2014/1/1,豐原,AMB_TEMP,14,14,14,13,12,12,12,...,22,22,21,19,17,16,15,15,15,15
1,2014/1/1,豐原,CH4,1.8,1.8,1.8,1.8,1.8,1.8,1.8,...,1.8,1.8,1.8,1.8,1.8,1.8,1.8,1.8,1.8,1.8
2,2014/1/1,豐原,CO,0.51,0.41,0.39,0.37,0.35,0.3,0.37,...,0.37,0.37,0.47,0.69,0.56,0.45,0.38,0.35,0.36,0.32
3,2014/1/1,豐原,NMHC,0.2,0.15,0.13,0.12,0.11,0.06,0.1,...,0.1,0.13,0.14,0.23,0.18,0.12,0.1,0.09,0.1,0.08
4,2014/1/1,豐原,NO,0.9,0.6,0.5,1.7,1.8,1.5,1.9,...,2.5,2.2,2.5,2.3,2.1,1.9,1.5,1.6,1.8,1.5
5,2014/1/1,豐原,NO2,16,9.2,8.2,6.9,6.8,3.8,6.9,...,11,11,22,28,19,12,8.1,7,6.9,6
6,2014/1/1,豐原,NOx,17,9.8,8.7,8.6,8.5,5.3,8.8,...,14,13,25,30,21,13,9.7,8.6,8.7,7.5
7,2014/1/1,豐原,O3,16,30,27,23,24,28,24,...,65,64,51,34,33,34,37,38,38,36
8,2014/1/1,豐原,PM10,56,50,48,35,25,12,4,...,52,51,66,85,85,63,46,36,42,42
9,2014/1/1,豐原,PM2.5,26,39,36,35,31,28,25,...,36,45,42,49,45,44,41,30,24,13
10,2014/1/1,豐原,RAINFALL,NR,NR,NR,NR,NR,NR,NR,...,NR,NR,NR,NR,NR,NR,NR,NR,NR,NR
11,2014/1/1,豐原,RH,77,68,67,74,72,73,74,...,47,49,56,67,72,69,70,70,70,69
12,2014/1/1,豐原,SO2,1.8,2,1.7,1.6,1.9,1.4,1.5,...,3.9,4.4,9.9,5.1,3.4,2.3,2,1.9,1.9,1.9
13,2014/1/1,豐原,THC,2,2,2,1.9,1.9,1.8,1.9,...,1.9,1.9,1.9,2.1,2,1.9,1.9,1.9,1.9,1.9
14,2014/1/1,豐原,WD_HR,37,80,57,76,110,106,101,...,307,304,307,124,118,121,113,112,106,110
15,2014/1/1,豐原,WIND_DIREC,35,79,2.4,55,94,116,106,...,313,305,291,124,119,118,114,108,102,111
16,2014/1/1,豐原,WIND_SPEED,1.4,1.8,1,0.6,1.7,2.5,2.5,...,2.5,2.2,1.4,2.2,2.8,3,2.6,2.7,2.1,2.1
17,2014/1/1,豐原,WS_HR,0.5,0.9,0.6,0.3,0.6,1.9,2,...,2.1,2.1,1.9,1,2.5,2.5,2.8,2.6,2.4,2.3
18,2014/1/2,豐原,AMB_TEMP,16,15,15,14,14,15,16,...,24,24,23,21,20,19,18,18,18,18
19,2014/1/2,豐原,CH4,1.8,1.8,1.8,1.8,1.8,1.8,1.8,...,1.8,1.8,1.8,1.8,1.8,1.8,1.8,1.8,1.8,1.8

In [5]:
test_data = pd.read_csv('test.csv', header=None)

In [6]:
test_data.head(20)

      0           1     2     3     4     5     6     7     8     9     10
0   id_0    AMB_TEMP    21    21    20    20    19    19    19    18    17
1   id_0         CH4   1.7   1.7   1.7   1.7   1.7   1.7   1.7   1.7   1.8
2   id_0          CO  0.39  0.36  0.36   0.4  0.53  0.55  0.34  0.31  0.23
3   id_0        NMHC  0.16  0.24  0.22  0.27  0.27  0.26  0.27  0.29   0.1
4   id_0          NO   1.3   1.3   1.3   1.3   1.4   1.6   1.2   1.1   0.9
5   id_0         NO2    17    14    13    14    18    21   8.9   9.4     5
6   id_0         NOx    18    16    14    15    20    23    10    10   5.8
7   id_0          O3    32    31    31    26    16    12    27    20    26
8   id_0        PM10    62    50    44    39    38    32    48    36    25
9   id_0       PM2.5    33    39    39    25    18    18    17     9     4
10  id_0    RAINFALL    NR    NR    NR    NR    NR    NR    NR    NR    NR
11  id_0          RH    83    85    87    87    86    85    78    81    80
12  id_0         SO2     2   1.8   1.8   1.8   2.1   2.6     2   2.3   2.4
13  id_0         THC   1.8   1.9   1.9     2     2     2     2     2   1.9
14  id_0       WD_HR    58    53    67    59    59    73    79    82   104
15  id_0  WIND_DIREC    57    44    73    44    56   115    45   107   103
16  id_0  WIND_SPEED   1.4   1.3   1.5   1.4   1.6   1.6   1.2   1.8   2.3
17  id_0       WS_HR     1   0.9   0.9   0.9   1.2   0.7     1   0.6   1.8
18  id_1    AMB_TEMP    14    13    13    13    13    13    13    12    13
19  id_1         CH4   1.8   1.8   1.8   1.8   1.8   1.8   1.7   1.7   1.8

In [7]:
test_data.shape

(4320, 11)

In [8]:
train_data.shape

(4320, 27)

In [9]:
x_data = train_data.iloc[:, 3:]
x_data = np.where(x_data == 'NR', 0, x_data)

In [10]:
x_data = x_data.astype(float)

In [11]:
x_data

array([[ 14.  ,  14.  ,  14.  , ...,  15.  ,  15.  ,  15.  ],
       [  1.8 ,   1.8 ,   1.8 , ...,   1.8 ,   1.8 ,   1.8 ],
       [  0.51,   0.41,   0.39, ...,   0.35,   0.36,   0.32],
       ...,
       [ 36.  ,  55.  ,  72.  , ..., 118.  , 100.  , 105.  ],
       [  1.9 ,   2.4 ,   1.9 , ...,   1.5 ,   2.  ,   2.  ],
       [  0.7 ,   0.8 ,   1.8 , ...,   1.6 ,   1.8 ,   2.  ]])

In [12]:
month_data = {}
for month in range(12):
    current_month_data = []
    for day in range(20):
        current_month_data.append(x_data[18 * (20 * month + day) : 18 * (20 * month + day + 1), :])
    month_data[month] = np.concatenate(current_month_data, axis=1)

In [13]:
month_data[0].shape

(18, 480)

In [14]:
x_train = np.empty([12 * 471, 18 * 9], dtype=float)
y_train = np.empty([12 * 471, 1], dtype=float)

In [15]:
for month in range(12):
    for day in range(20):
        for hour in range(24):
            if day == 19 and hour > 14:
                continue
            x_train[471 * month + day * 24 + hour, :] = month_data[month][:, day * 24 + hour:day * 24 + hour + 9].reshape(1, -1)
            y_train[month * 471 + day * 24 + hour, 0] = month_data[month][9, day * 24 + hour + 9]

In [16]:
x_train

array([[14. , 14. , 14. , ...,  2. ,  2. ,  0.5],
       [14. , 14. , 13. , ...,  2. ,  0.5,  0.3],
       [14. , 13. , 12. , ...,  0.5,  0.3,  0.8],
       ...,
       [17. , 18. , 19. , ...,  1.1,  1.4,  1.3],
       [18. , 19. , 18. , ...,  1.4,  1.3,  1.6],
       [19. , 18. , 17. , ...,  1.3,  1.6,  1.8]])

In [17]:
y_train

array([[30.],
       [41.],
       [44.],
       ...,
       [17.],
       [24.],
       [29.]])

In [18]:
train_data.iloc[9, :]

日期    2014/1/1
測站          豐原
測項       PM2.5
0           26
1           39
2           36
3           35
4           31
5           28
6           25
7           20
8           19
9           30
10          41
11          44
12          33
13          37
14          36
15          45
16          42
17          49
18          45
19          44
20          41
21          30
22          24
23          13
Name: 9, dtype: object

In [19]:
x_train_mean = np.mean(x_train, axis=0)

In [20]:
x_train_std = np.std(x_train, axis=0)

In [21]:
x_train_mean.shape, x_train_std.shape

((162,), (162,))

In [22]:
x_train.shape

(5652, 162)

In [23]:
normal_x_train = (x_train - x_train_mean) / x_train_std

In [24]:
normal_x_train[0]

array([-1.35825331, -1.35883937, -1.359222  , -1.51812675, -1.67669103,
       -1.67597791, -1.67517667, -1.67420959, -1.19714582,  0.77544377,
        0.77626641,  0.77736709,  0.77764454,  0.77857257,  0.77885864,
        0.77932715,  0.77951796,  0.78007373,  0.37090643,  0.06459709,
        0.00319053, -0.05878347, -0.12063637, -0.27410004, -0.05920897,
        0.24824278,  1.20115603,  0.57293427,  0.0939535 , -0.09971441,
       -0.1979345 , -0.29478871, -0.7708553 , -0.39102764, -0.10551817,
        1.13325467, -0.54328476, -0.67466953, -0.71919559, -0.19800779,
       -0.15472949, -0.28537553, -0.11121269,  0.02013846,  1.94134554,
        0.94869554, -0.14813488, -0.31066014, -0.52201827, -0.53991927,
       -1.0239315 , -0.52592285, -0.38098762,  0.77923341,  0.62460705,
       -0.32264691, -0.46851971, -0.48372301, -0.49855755, -0.91980584,
       -0.46088395, -0.31608174,  1.27515899, -0.84686226, -0.10343027,
       -0.26497459, -0.4790525 , -0.42660712, -0.21451509, -0.42795087,
       -0.5349638 , -0.58872416,  0.51017812,  0.2820103 ,  0.20535555,
       -0.29054327, -0.67256476, -1.16866117, -1.47470059, -1.55262038,
       -1.21089545,  0.27889755,  1.05839335,  0.88014061,  0.82065821,
        0.57961575,  0.39893127,  0.21838973, -0.08226916, -0.14272026,
       -0.09879803, -0.09854415, -0.09824468, -0.09821037, -0.09812583,
       -0.09802486, -0.09799055, -0.09799055, -0.09799055,  0.28379851,
       -0.38377149, -0.45603404,  0.06797656, -0.07995218, -0.00432625,
        0.07124627, -0.00315304, -0.52747191, -0.52760681, -0.41794243,
       -0.58323327, -0.63912107, -0.47588372, -0.75026704, -0.69624099,
       -0.64196762,  1.27304467,  0.88137552,  0.88201895,  0.88081831,
        0.33015542,  0.3294752 , -0.21861218,  0.32976505,  0.33039252,
        1.42801429, -1.2458448 , -0.79835564, -1.03883804, -0.84073395,
       -0.48646826, -0.52774988, -0.57986673, -0.54869874, -0.34109199,
       -1.30411437, -0.8408487 , -1.64884991, -1.09440912, -0.68310949,
       -0.45226166, -0.55760135, -0.68389995,  0.7684249 , -0.83983357,
       -0.46768335, -1.21749619, -1.59208393, -0.56489316,  0.18312957,
        0.18190364, -0.28611588, -1.59862324, -1.13897235, -0.76416996,
       -1.04470765, -1.324569  , -1.04394223,  0.17318839,  0.26650729,
        0.2656797 , -1.14082131])

In [25]:
import math

In [26]:
x_tra = normal_x_train[:math.floor(len(x_train) * 0.8), :]
y_tra = y_train[:math.floor(len(x_train) * 0.8)]
x_val = normal_x_train[math.floor(len(x_train) * 0.8):, :]
y_val = y_train[math.floor(len(x_train) * 0.8):]

In [27]:
x_tra.shape, y_tra.shape, x_val.shape, y_val.shape

((4521, 162), (4521, 1), (1131, 162), (1131, 1))

## 训练

In [28]:
dimension = 18 * 9 + 1
w = np.zeros((dimension, 1))
x_tra = np.concatenate([np.ones((4521, 1)), x_tra], axis=1)
learning_rate = 0.001

In [29]:
iter_time = 5000

In [30]:
x_tra.shape

(4521, 163)

In [31]:
for t in range(iter_time):
    y_predict = np.dot(x_tra, w)
    diff = y_predict - y_tra
    loss = np.sum(np.power(diff, 2)) / 4521
    if t % 500 == 0:
        print("loss is", loss)
    gradient = np.dot(x_tra.T, diff) * 2 / 4521
    w -= learning_rate * gradient

loss is 741.9953550099535
loss is 123.37561021642455
loss is 60.5328699396024
loss is 47.99732806202014
loss is 44.01698108685079
loss is 41.997208036361336
loss is 40.65890066669445
loss is 39.663388538494694
loss is 38.881384832293136
loss is 38.247098989240726

In [32]:
test_data.head(20)

      0           1     2     3     4     5     6     7     8     9     10
0   id_0    AMB_TEMP    21    21    20    20    19    19    19    18    17
1   id_0         CH4   1.7   1.7   1.7   1.7   1.7   1.7   1.7   1.7   1.8
2   id_0          CO  0.39  0.36  0.36   0.4  0.53  0.55  0.34  0.31  0.23
3   id_0        NMHC  0.16  0.24  0.22  0.27  0.27  0.26  0.27  0.29   0.1
4   id_0          NO   1.3   1.3   1.3   1.3   1.4   1.6   1.2   1.1   0.9
5   id_0         NO2    17    14    13    14    18    21   8.9   9.4     5
6   id_0         NOx    18    16    14    15    20    23    10    10   5.8
7   id_0          O3    32    31    31    26    16    12    27    20    26
8   id_0        PM10    62    50    44    39    38    32    48    36    25
9   id_0       PM2.5    33    39    39    25    18    18    17     9     4
10  id_0    RAINFALL    NR    NR    NR    NR    NR    NR    NR    NR    NR
11  id_0          RH    83    85    87    87    86    85    78    81    80
12  id_0         SO2     2   1.8   1.8   1.8   2.1   2.6     2   2.3   2.4
13  id_0         THC   1.8   1.9   1.9     2     2     2     2     2   1.9
14  id_0       WD_HR    58    53    67    59    59    73    79    82   104
15  id_0  WIND_DIREC    57    44    73    44    56   115    45   107   103
16  id_0  WIND_SPEED   1.4   1.3   1.5   1.4   1.6   1.6   1.2   1.8   2.3
17  id_0       WS_HR     1   0.9   0.9   0.9   1.2   0.7     1   0.6   1.8
18  id_1    AMB_TEMP    14    13    13    13    13    13    13    12    13
19  id_1         CH4   1.8   1.8   1.8   1.8   1.8   1.8   1.7   1.7   1.8

In [33]:
test_data.tail(20)

          0           1     2     3     4     5     6     7     8     9     10
4300  id_238  WIND_SPEED   1.4   1.7   1.9   1.7   1.6   1.4   0.6   0.8   1.2
4301  id_238       WS_HR   1.4   1.7   1.6   1.8   1.8   1.6   0.6   0.5   0.5
4302  id_239    AMB_TEMP    14    14    14    14    15    15    15    15    17
4303  id_239         CH4   1.7   1.7   1.7   1.7   1.7   1.7   1.7   1.7   1.7
4304  id_239          CO  0.27  0.24  0.23   0.2  0.17  0.16  0.16  0.16  0.18
4305  id_239        NMHC  0.09  0.08  0.07  0.06  0.04  0.03  0.03  0.03  0.04
4306  id_239          NO   0.8   1.3   1.2   1.7   1.4   1.5   1.3   1.5   1.6
4307  id_239         NO2   6.9   5.9   5.3   3.1   2.2   1.7   1.8   2.2   3.3
4308  id_239         NOx   7.6   7.2   6.5   4.8   3.7   3.2   3.1   3.7   4.9
4309  id_239          O3    56    56    53    49    47    45    43    42    42
4310  id_239        PM10    21    32    30    27    14    26    22    25     6
4311  id_239       PM2.5    22    20    20    14    12    16    13    16    16
4312  id_239    RAINFALL    NR    NR    NR    NR    NR    NR    NR    NR    NR
4313  id_239          RH    47    45    45    44    42    41    41    40    38
4314  id_239         SO2     2     2   1.8   1.6   1.5   1.5   1.4   1.5   1.7
4315  id_239         THC   1.8   1.8   1.8   1.8   1.7   1.7   1.7   1.7   1.7
4316  id_239       WD_HR    80    92    95    95    96    97    96    96    84
4317  id_239  WIND_DIREC    76    99    93    97    93    94    98    97    65
4318  id_239  WIND_SPEED   2.2   3.2   2.5   3.6     5   4.2   5.7   4.9   3.6
4319  id_239       WS_HR   1.7   2.8   2.6   3.3   3.5     5   4.9   5.2   3.6

In [34]:
x_test = test_data.iloc[:, 2:].values

In [35]:
x_test.shape

(4320, 9)

In [36]:
x_test.dtype

dtype('O')

In [37]:
x_test = np.where(x_test == 'NR', 0, x_test)

In [38]:
x_test = x_test.astype(float)

In [39]:
x_test

array([[21.  , 21.  , 20.  , ..., 19.  , 18.  , 17.  ],
       [ 1.7 ,  1.7 ,  1.7 , ...,  1.7 ,  1.7 ,  1.8 ],
       [ 0.39,  0.36,  0.36, ...,  0.34,  0.31,  0.23],
       ...,
       [76.  , 99.  , 93.  , ..., 98.  , 97.  , 65.  ],
       [ 2.2 ,  3.2 ,  2.5 , ...,  5.7 ,  4.9 ,  3.6 ],
       [ 1.7 ,  2.8 ,  2.6 , ...,  4.9 ,  5.2 ,  3.6 ]])

In [40]:
test = []
for i in range(240):
    test.append(x_test[i * 18: (i + 1) * 18, :].reshape(1, -1))

In [41]:
test = np.concatenate(test, axis=0)

In [42]:
test.shape

(240, 162)

In [43]:
np.concatenate([np.ones((240, 1)), test], axis=1)

array([[ 1. , 21. , 21. , ...,  1. ,  0.6,  1.8],
       [ 1. , 14. , 13. , ...,  1.9,  1.6,  1.2],
       [ 1. , 32. , 31. , ...,  0.3,  0.6,  1.1],
       ...,
       [ 1. , 25. , 26. , ...,  2. ,  1.5,  3. ],
       [ 1. , 11. , 11. , ...,  0.6,  0.5,  0.5],
       [ 1. , 14. , 14. , ...,  4.9,  5.2,  3.6]])

In [44]:
test_predict = np.dot(np.concatenate([np.ones((240, 1)), test], axis=1), w)

In [45]:
test_predict

array([[ 7.95411699e+01],
       [ 2.40721551e+02],
       [ 3.65212855e+02],
       [ 9.79781892e+01],
       [ 4.54312015e+02],
       [ 3.50896333e+02],
       [ 3.18178645e+02],
       [ 5.61397351e+02],
       [ 2.67983363e+02],
       [ 9.22275603e+02],
       [ 2.26387843e+02],
       [ 1.39396293e+02],
       [ 9.64784980e+02],
       [ 8.80591735e+02],
       [ 3.71146000e+02],
       [ 1.69865801e+02],
       [ 4.88763534e+02],
       [ 1.06583651e+03],
       [-2.26130515e+01],
       [ 2.38041433e+02],
       [ 6.72173791e+02],
       [ 1.23373152e+03],
       [ 6.69292082e+01],
       [ 2.42340770e+02],
       [ 2.44844159e+02],
       [ 6.45110478e+02],
       [ 1.99766482e+02],
       [ 1.28311631e+03],
       [ 5.07838029e+01],
       [ 8.88731060e+02],
       [ 3.09564602e+02],
       [ 9.58329057e+01],
       [-3.29462184e+01],
       [ 4.02645671e+02],
       [ 5.84424200e+02],
       [ 5.20060299e+02],
       [ 7.00391396e+02],
       [ 4.98371979e+02],
       [ 7.20411500e+02],
       [ 6.30771679e+02],
       [ 7.06382773e+01],
       [ 6.68938369e+02],
       [ 4.62964863e+02],
       [ 7.78196694e+02],
       [ 2.71543587e+02],
       [ 5.70327785e+02],
       [ 3.65351349e+02],
       [ 1.38501509e+02],
       [ 3.17771265e+02],
       [ 4.02698690e+02],
       [ 3.60631176e+02],
       [ 1.19845593e+02],
       [ 4.15696036e+02],
       [ 8.58259600e+02],
       [ 2.49783922e+02],
       [ 6.07357270e+02],
       [ 4.97552660e+02],
       [ 3.17726238e+02],
       [ 9.86500354e+02],
       [ 3.02707292e+02],
       [ 3.28384721e+02],
       [ 5.87644815e+02],
       [ 1.65238133e+02],
       [ 7.88908627e+02],
       [ 2.15930229e+02],
       [ 2.43733068e+02],
       [ 2.67046438e+02],
       [-4.72286628e+01],
       [ 7.57465333e+02],
       [ 5.01760782e+02],
       [ 2.49301179e+02],
       [ 5.03581351e+02],
       [ 9.61015988e+02],
       [ 7.89074560e+01],
       [ 1.98636529e+02],
       [ 8.92750044e+01],
       [ 7.56200561e+02],
       [ 2.45022397e+02],
       [ 4.47451302e+02],
       [ 3.65148622e+02],
       [ 4.42011880e+02],
       [ 6.13590300e+02],
       [ 3.38517363e+02],
       [ 1.41345261e+03],
       [ 5.31353865e+02],
       [ 4.01045967e+02],
       [ 4.09871359e+02],
       [ 4.44202415e+02],
       [ 3.85476207e+02],
       [ 3.72649371e+02],
       [ 5.02325874e+02],
       [ 5.53106405e+02],
       [ 8.11219607e+01],
       [ 6.44007060e+02],
       [ 6.71496267e+02],
       [ 2.56424118e+02],
       [ 5.58882668e+02],
       [ 1.32696616e+02],
       [ 3.91635456e+02],
       [ 6.33100615e+01],
       [ 2.61768999e+02],
       [ 5.19206983e+02],
       [ 1.98125342e+02],
       [ 2.36561098e+02],
       [ 3.93633950e+02],
       [ 5.71827122e+02],
       [ 4.39845994e+02],
       [ 6.49491911e+01],
       [ 1.39312772e+02],
       [ 1.22750103e+03],
       [ 7.45553520e+02],
       [ 2.07909451e+02],
       [ 3.80954993e+02],
       [ 2.67775812e+02],
       [ 1.91989387e+02],
       [ 3.86727377e+02],
       [ 3.41075904e+02],
       [ 1.11635266e+02],
       [ 2.91093695e+02],
       [ 2.64564627e+02],
       [ 1.16547035e+03],
       [ 3.33096489e+02],
       [ 4.37411423e+02],
       [ 4.02582893e+02],
       [ 1.09628005e+02],
       [ 7.48333922e+02],
       [ 1.50489877e+02],
       [ 1.94583882e+02],
       [ 5.10943031e+02],
       [ 1.13534247e+03],
       [ 3.18057279e+02],
       [ 2.33238300e+02],
       [ 8.40405254e+02],
       [ 1.78738275e+02],
       [ 2.40469157e+02],
       [ 1.73085903e+01],
       [ 2.05836715e+02],
       [ 8.64239087e+02],
       [ 2.47265484e+02],
       [ 8.08247111e+01],
       [ 4.13369197e+02],
       [ 3.75576304e+02],
       [ 6.46148309e+02],
       [ 5.28265904e+02],
       [ 2.10249673e+02],
       [ 4.16728922e+02],
       [ 1.39897657e+02],
       [ 8.35126507e+02],
       [ 2.36780895e+02],
       [ 5.65849690e+02],
       [ 1.21727508e+02],
       [ 9.38318003e+01],
       [ 4.54754604e+02],
       [ 7.75255223e+01],
       [ 1.98317103e+02],
       [ 6.11736917e+02],
       [ 1.10327118e+02],
       [ 5.49372785e+02],
       [ 2.10857553e+02],
       [ 3.05434780e+02],
       [ 6.81209497e+02],
       [ 2.64566502e+02],
       [ 1.15200958e+02],
       [ 9.24879449e+01],
       [ 9.13802105e+02],
       [ 4.22251142e+02],
       [ 3.21597247e+00],
       [ 2.37629601e+02],
       [ 9.90980505e+02],
       [ 2.46850803e+02],
       [ 1.10595249e+03],
       [ 5.91284923e+02],
       [ 3.38743693e+02],
       [ 2.99328072e+02],
       [ 9.13383651e+02],
       [ 2.42158525e+02],
       [ 3.18236260e+02],
       [ 5.20731166e+02],
       [ 1.46688461e+02],
       [ 4.51578079e+02],
       [ 2.32082991e+02],
       [ 1.15345978e+02],
       [ 8.01770784e+02],
       [ 5.87699106e+02],
       [ 2.80198173e+02],
       [ 5.23275543e+02],
       [ 4.64319491e+02],
       [ 1.15278261e+03],
       [ 1.73516490e+02],
       [ 8.57976392e+02],
       [ 5.61747200e+02],
       [ 1.89461476e+02],
       [ 3.22693558e+02],
       [-4.95779884e+01],
       [ 3.05906468e+02],
       [-4.94841773e+00],
       [ 5.41706280e+02],
       [ 2.35688088e+01],
       [ 3.01375462e+02],
       [ 1.10484843e+03],
       [ 3.83016391e+02],
       [ 3.16450448e+02],
       [ 1.00394298e+03],
       [ 1.63913889e+02],
       [ 1.52628602e+02],
       [ 1.40192966e+02],
       [ 1.21117619e+02],
       [ 4.69429365e-01],
       [ 2.00233718e+03],
       [ 2.84782936e+02],
       [ 1.98485635e+02],
       [ 2.12167884e+02],
       [ 5.20281224e+02],
       [ 5.44195290e+02],
       [ 3.11808555e+02],
       [ 4.99022145e+02],
       [ 1.22653245e+03],
       [ 6.40426451e+00],
       [ 2.01854885e+02],
       [ 5.52556447e+02],
       [ 2.55154162e+02],
       [ 1.08882987e+02],
       [ 1.99176874e+03],
       [ 1.31954304e+02],
       [ 2.50459470e+02],
       [ 9.64857480e+02],
       [ 2.40675383e+02],
       [ 2.78119056e+02],
       [ 1.46633119e+02],
       [ 7.27775221e+01],
       [ 6.63072257e+02],
       [ 2.92892060e+02],
       [ 7.57133214e+02],
       [ 6.40785245e+02],
       [ 2.32964940e+02],
       [ 5.76684555e+02],
       [ 1.16131953e+03],
       [ 6.21651136e+02],
       [ 6.23256920e+01],
       [ 2.17575115e+02]])

In [46]:
ids = []
for i in range(240):
    ids.append('id_{}'.format(i))

In [47]:
ids = np.array(ids)

In [48]:
ids.shape

(240,)

In [49]:
ids = ids.reshape(-1, 1)

In [50]:
result = np.concatenate([ids, test_predict], axis=1)

In [51]:
result_df = pd.DataFrame(result, columns=['id', 'value'])

In [52]:
result_df

         id               value
0      id_0   79.54116990287184
1      id_1   240.7215511398124
2      id_2   365.2128549611628
3      id_3   97.97818917173495
4      id_4   454.3120149963716
..      ...                 ...
235  id_235   576.6845554698012
236  id_236  1161.3195269003188
237  id_237   621.6511358586424
238  id_238  62.325692003254055
239  id_239   217.5751146126081

[240 rows x 2 columns]

In [54]:
result_df.to_csv('result.csv', index=False)

## Adagrad

In [73]:
x_tra = normal_x_train[:math.floor(len(x_train) * 0.8), :]
y_tra = y_train[:math.floor(len(x_train) * 0.8)]
x_val = normal_x_train[math.floor(len(x_train) * 0.8):, :]
y_val = y_train[math.floor(len(x_train) * 0.8):]

In [74]:
dimension = 18 * 9 + 1
w = np.zeros((dimension, 1))
x_tra = np.concatenate([np.ones((4521, 1)), x_tra], axis=1)
learning_rate = 100
adagrad = np.zeros([dimension, 1])
eps = 0.0000000001

In [75]:
iter_time = 10000

In [76]:
for t in range(iter_time):
    y_predict = np.dot(x_tra, w)
    diff = y_predict - y_tra
    loss = np.sum(np.power(diff, 2)) / 4521
    if t % 500 == 0:
        print("loss is", loss)
    gradient = np.dot(x_tra.T, diff) * 2 / 4521
    adagrad += gradient ** 2
    w -= learning_rate * gradient / np.sqrt(adagrad + eps)

loss is 741.9953550099535
loss is 42.491721766157106
loss is 35.68328970070171
loss is 34.03388750500748
loss is 33.42365097310272
loss is 33.13157134528521
loss is 32.971661904884726
loss is 32.878573576126456
loss is 32.82267664417916
loss is 32.78839518050184
loss is 32.766946695358484
loss is 32.75321487551343
loss is 32.744167912617804
loss is 32.73799015086264
loss is 32.733585889604576
loss is 32.73028975428972
loss is 32.72769543031729
loss is 32.72555346732013
loss is 32.723709873572524
loss is 32.722069009706054